### ISSUE TITLE
is there a way to use my own voice rather than using voice presets?

### ISSUE THREAD

**Issue by netronom** [suno-ai/bark#169]
Hello,
I really love the project and the progress the team is making 
but is there a way to make use of my voice rather than using the voice presets 
as i can speak English, Japanese, and Russian.

**Comment by etmyhome** [comment]
@gkucsko  any updates ?

**Comment by gkucsko** [comment]
we are looking into ways of verifying your own voice, but these things are much harder to control in a fully public releases, so might be reserved for suno studio where we can host and control the use of the models, but let's see, defo working on it

**Comment by CarlKenner** [comment]
> Hello, I really love the project and the progress the team is making but is there a way to make use of my voice rather than using the voice presets as i can speak English, Japanese, and Russian.

The voice-cloning forks don't really work right now and aren't worth trying. But other people will probably eventually get it working.

**Comment by 3dluvr** [comment]
> we are looking into ways of verifying your own voice, but these things are much harder to control in a fully public releases, so might be reserved for suno studio where we can host and control the use of the models, but let's see, defo working on it

@gkucsko

Is this some kind of a "save the children" and "save the planet" thing, to allegedly protect the public from AI misuse?

It is silly and ridiculous.

As a member of the general public, I can tell you that you are not protecting anyone from anything by holding back. "Malicious actors" already have access to similar, or better technologies, so all you are doing is giving them an advantage over us, the normal people, who are being left behind with all this AI hold back that is happening now.

I do not know whether this is deliberate or not, and I wouldn't exclude that possibility, since Plebis have been routinely and systematically screwed over for centuries.

Obviously do what you want and whatever aligns with your belief system, but know that you are doing public dis-service by holding back, just like everyone else who is crying "the world is ending" right now because of the AI.

**Comment by gkucsko** [comment]
Closing for now since this is not a functional issue. Feel free to move to discussions.

**Comment by etmyhome** [comment]
@gkucsko  We should not restrict the entire community's experience merely because of the actions of a few bad actors
