### ISSUE TITLE
Is it real to run this by 8Gb VRAM ? 

### ISSUE THREAD

**Issue by LuchunPen** [suno-ai/bark#192]
I'm trying to run by1070 8Gb, but have only this: 

CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 8.00 GiB total capacity; 7.33 GiB already allocated; 0 bytes free; 7.36 GiB reserved in total by PyTorch)

Could you explayn is it real to run and what I have to do ?

**Comment by Acephalia** [comment]
You can run it. Go to generation.py in the Bark folder and set SUNO_USE_SMALL_MODELS to True. This should let you download smaller models and have no issue with generation with this turned on.

**Comment by dtheb** [comment]
@Acephalia Any idea how does it affect the results?

**Comment by Acephalia** [comment]
In my opinion it is currently only usable for a little bit of fun and experimentation. 

I don’t know if there is any quality drop between the full model and smaller models the samples provided are cherry picked and you are not going to get that kind of output without a lot of work and generations. Haven’t eeen anyone else say otherwise yet either. 

But remember it’s still pretty amazing and barely in its infancy, and if we look at how fast things like stable diffusion etc have developed it shouldn’t be too long before Bark evolves into something pretty substantial.  

I found[this fork](https://github.com/C0untFloyd/bark-gui) it is the best GUI option currently imho. If you are still having trouble with this, give that one a go.

**Comment by gkucsko** [comment]
gonna close since a bit off topic for the issue
