### ISSUE TITLE
Support for Portuguese (pt)

### ISSUE THREAD

**Issue by ricardomatias** [suno-ai/bark#58]
The examples provided are in pt-br Portuguese from Brazil and not in Portuguese from Portugal. I suggest replacing the Portuguese flag with a Brazilian one in the documents and adding pt-br instead of pt.

Would be much appreciated to have support for Portuguese from Portugal.

**Comment by gkucsko** [comment]
the model should have both (although the distribution might be biased and maybe the speaker prompts happen to be only br). if you generate pt text multiple times you should hopefully at some point get portugal. then you can save that as a prompt for future use. let us know if it works, would be good to know!

**Comment by maxbrito500** [comment]
that is still very random-like. It would be clearer to distinguish them since they are definitively very different, including on grammar level. Most people might be quick to assume a similar case as british vs american english albeit on reality would place portuguese speakers at odds trying to understand each other 30% of times.

**Comment by gkucsko** [comment]
Thanks super helpful. Ya we can definitely split them out when we train the next generation of models. For now unfortunately no other way to fix it after training

**Comment by maxbrito500** [comment]
No worries nor rush. Truly appreciate the effort you've put into this project. It is fantastic.
